### PR TITLE
Fixes the focus in tailoring window when (un)checking checkboxes

### LINKED ISSUE #128: Checking checkboxes in the tailoring window temporarily loses focus on the tree widget
You can observe the tree widget changing colors from black to grey and back as it loses focus every time you click on anything. This is probably easy to fix by manipulating updates and redraws while changing the tree.

### PR DESCRIPTION
**Pull request by WesleyCeraso**
Fixes #128

Signed-off-by: Wesley Ceraso Prudencio <wcerasop@redhat.com>

### CODE REVIEW

File: src/TailoringWindow.cpp [hunk 1]
```diff
@@ -267,9 +267,12 @@ void TailoringWindow::synchronizeTreeItem()
     // If QTreeWidget remains visible during the sync, it'll recalculate its geometry for each checked
     // row. Configuring "visible" as false seems to be the only way to avoid entering the "if" in
     // https://github.com/qt/qt/blob/4.8/src/gui/itemviews/qabstractitemview.cpp#L3190
+    QWidget * focused = QApplication::focusWidget();
```
Comment (mpreisler) [inline src/TailoringWindow.cpp]: coding style

File: src/TailoringWindow.cpp [hunk 2]
```diff
@@ -267,9 +267,12 @@ void TailoringWindow::synchronizeTreeItem()
...
     mUI.itemsTree->setVisible(false);
     synchronizeTreeItemSelections(mBenchmarkItem);
     mUI.itemsTree->setVisible(true);
+    // The widget loses focus when it becomes invisible, so we set it again
+    if (focused) focused->setFocus();
```
Comment (mpreisler) [inline src/TailoringWindow.cpp]: coding style

File: src/TailoringWindow.cpp (hunk 1 above)
Comment (mpreisler) [inline src/TailoringWindow.cpp]: I also think a comment should explain why we are doing all this.
